Caching disabled explicitly for extract.

Step extract has started.

Failed to run step extract.

GlobalHydra is already initialized, call GlobalHydra.instance().clear() if you want to re-initialize
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/zenml/orchestrators/step_launcher.py", line 230, in launch
    self._run_step(
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/zenml/orchestrators/step_launcher.py", line 460, in _run_step
    self._run_step_without_step_operator(
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/zenml/orchestrators/step_launcher.py", line 535, in _run_step_without_step_operator
    runner.run(
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/zenml/orchestrators/step_runner.py", line 199, in run
    return_values = step_instance.call_entrypoint(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/zenml/steps/base_step.py", line 606, in call_entrypoint
    return self.entrypoint(**validated_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Sofa/Desktop/Innopolis/MLOps/ApartmentPrice/services/airflow/dags/data_prepare.py", line 24, in extract
    df, version = read_datastore()
                  ^^^^^^^^^^^^^^^^
  File "/Users/Sofa/Desktop/Innopolis/MLOps/ApartmentPrice/src/data.py", line 117, in read_datastore
    initialize(config_path="../configs", version_base="1.1")
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/hydra/initialize.py", line 91, in __init__
    Hydra.create_main_hydra_file_or_module(
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 53, in create_main_hydra_file_or_module
    return Hydra.create_main_hydra2(job_name, config_search_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 68, in create_main_hydra2
    GlobalHydra.instance().initialize(hydra)
  File "/opt/homebrew/anaconda3/envs/mlops_9/lib/python3.11/site-packages/hydra/core/global_hydra.py", line 16, in initialize
    raise ValueError(
ValueError: GlobalHydra is already initialized, call GlobalHydra.instance().clear() if you want to re-initialize

